[features]
seeds = false
[programs.devnet]
sol_ipl = "HDa6A4wLjEymb8Cv3UGeGBnFUNCUEMpoiVBbkTKAkfrt"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/anoushkkharangate/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
